#!/usr/bin/env node
'use strict'
const fs=require('fs');const path=require('path');const crypto=require('crypto');const {execFileSync}=require('child_process')
const ROOT='C:\\Users\\Deglu\\.hermes';const OUT=path.join(ROOT,'reports','repository_audit');const MATRIX=path.join(ROOT,'tools','swarm_goals','all_projects_audit_matrix.json')
const IGNORE=new Set(['node_modules','.cache','.venv','venv','dist','build','__pycache__','.agents','.codex','logs','tmp'])
function git(repo,args,fallback=''){try{return execFileSync('git',['-C',repo,...args],{encoding:'utf8',timeout:20000,maxBuffer:30*1024*1024,stdio:['ignore','pipe','ignore']}).trim()}catch(_){return fallback}}
function discover(root,maxDepth=5){const found=new Set();function walk(dir,depth){if(depth>maxDepth)return;let es;try{es=fs.readdirSync(dir,{withFileTypes:true})}catch(_){return}
  if(es.some(e=>e.name==='.git')&&git(dir,['rev-parse','--is-inside-work-tree'])==='true'){found.add(path.resolve(dir));return}for(const e of es){if(!e.isDirectory()||IGNORE.has(e.name)||e.name.startsWith('$'))continue;walk(path.join(dir,e.name),depth+1)}}walk(root,0);return[...found].sort()}
function binary(buf){return buf.subarray(0,Math.min(buf.length,8000)).includes(0)}
function lang(ext){return({'.js':'JavaScript','.cjs':'JavaScript','.mjs':'JavaScript','.ts':'TypeScript','.tsx':'TypeScript','.py':'Python','.rs':'Rust','.go':'Go','.java':'Java','.cs':'C#','.php':'PHP','.rb':'Ruby','.html':'HTML','.css':'CSS','.scss':'SCSS','.sql':'SQL','.md':'Markdown','.json':'JSON'})[ext]||'Other'}
function analyze(repo){const files=git(repo,['ls-files','-z']).split('\0').filter(Boolean);let loc=0,analyzed=0,todo=0,mocks=0,tests=0;const langs={},largest=[]
  for(const rel of files){const full=path.join(repo,rel);let st;try{st=fs.statSync(full)}catch(_){continue}largest.push({file:rel.replace(/\\/g,'/'),bytes:st.size});if(st.size>5*1024*1024)continue
    let buf;try{buf=fs.readFileSync(full)}catch(_){continue}if(binary(buf))continue;const text=buf.toString('utf8');const lines=text.length?(text.match(/\n/g)||[]).length+1:0;loc+=lines;analyzed++
    const l=lang(path.extname(rel).toLowerCase());langs[l]=(langs[l]||0)+lines;todo+=(text.match(/\b(TODO|FIXME|XXX)\b/g)||[]).length;mocks+=(text.match(/\b(MOCK_DATA|fake_[A-Za-z0-9_]*|hardcoded)\b/g)||[]).length
    if(/(^|[\\/])(__tests__|tests?|spec)([\\/]|\.)/i.test(rel))tests++}
  const status=git(repo,['status','--porcelain=v1']);return{repository:path.basename(repo),path:repo,branch:git(repo,['branch','--show-current'],'(detached)'),head:git(repo,['rev-parse','HEAD'],null),last_commit_at:git(repo,['log','-1','--format=%cI'],null),dirty:Boolean(status),changed_paths:status?status.split(/\r?\n/).length:0,tracked_files:files.length,analyzed_text_files:analyzed,lines_of_text:loc,test_files:tests,todo_fixme_signals:todo,mock_or_hardcode_signals:mocks,languages_by_lines:Object.fromEntries(Object.entries(langs).sort((a,b)=>b[1]-a[1])),largest_tracked_files:largest.sort((a,b)=>b.bytes-a.bytes).slice(0,10),evidence:{file_inventory:'git ls-files -z',revision:'git rev-parse HEAD',worktree:'git status --porcelain=v1'},limitations:['Static inventory only; no claim that tests, security scans, or runtime validation passed.']}}
function md(r){const rows=r.repositories.map(x=>`| ${x.repository} | ${x.branch} | ${x.tracked_files} | ${x.lines_of_text} | ${x.test_files} | ${x.dirty?'DIRTY':'clean'} |`).join('\n')
  return`# Audit reale delle repository Hermes\n\nGenerato: ${r.generated_at}\n\n## Executive Summary\n\nSono state individuate **${r.repository_count} repository Git reali**. Il precedente job da 10 ore non conteneva finding verificabili; questo report usa esclusivamente comandi Git e lettura dei file tracciati. Non equivale a un penetration test né certifica che build e test passino.\n\n## Inventario verificato\n\n| Repository | Branch | File tracciati | Linee testo | Test file | Worktree |\n|---|---:|---:|---:|---:|---|\n${rows}\n\n## Segnali da approfondire\n\n${r.repositories.map(x=>`### ${x.repository}\n\n- HEAD: \`${x.head||'non disponibile'}\`\n- Ultimo commit: ${x.last_commit_at||'non disponibile'}\n- TODO/FIXME/XXX: ${x.todo_fixme_signals}\n- Segnali mock/fake/hardcoded: ${x.mock_or_hardcode_signals}\n- File modificati/non tracciati: ${x.changed_paths}\n`).join('\n')}\n## Prossimi passi raccomandati\n\n1. Eseguire build e test per repository in job separati, salvando exit code e log.\n2. Revisionare prima i repository con worktree sporco e molti segnali mock/hardcoded.\n3. Eseguire scansioni segreti e dipendenze senza attribuire un esito finché i validator non terminano.\n\n## Caveat e assunzioni\n\n- Conteggi basati solo sui file tracciati da Git, esclusi binari e file oltre 5 MB.\n- La scoperta è limitata a cinque livelli sotto la root Hermes e ignora cache, ambienti virtuali e dipendenze.\n- Nessun punteggio di qualità viene calcolato senza una metrica validata.\n`}
function main(){fs.mkdirSync(OUT,{recursive:true});const repos=discover(ROOT).map(analyze);const generated=new Date().toISOString();const report={schema_version:'1.0.0',generated_at:generated,root:ROOT,method:'deterministic_git_inventory',repository_count:repos.length,repositories:repos};report.report_sha256=crypto.createHash('sha256').update(JSON.stringify(report)).digest('hex');const stamp=generated.slice(0,10),jp=path.join(OUT,`repository_audit_${stamp}.json`),mp=path.join(OUT,`repository_audit_${stamp}.md`);fs.writeFileSync(jp,JSON.stringify(report,null,2));fs.writeFileSync(mp,md(report));fs.writeFileSync(MATRIX,JSON.stringify(report,null,2));console.log(JSON.stringify({status:'completed',repositories:repos.length,json:jp,markdown:mp,matrix:MATRIX},null,2));if(!repos.length)process.exitCode=2}
try{main()}catch(e){console.error(e.stack||e.message);process.exit(1)}
